name: korean_vocab
description: "Korean Vocabulary Learning App with Smart SRS"
publish_to: 'none'

version: 2.2.0+4

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  sqflite: ^2.4.2
  path_provider: ^2.1.5
  flutter_tts: ^4.2.5
  flip_card: ^0.7.0
  swipable_stack: ^2.0.0
  get_it: ^9.2.1
  flutter_bloc: ^9.1.1
  equatable: ^2.0.8
  image_picker: ^1.2.1
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
